# Force explicit compression headers
[[headers]]
  for = "/*"
  [headers.values]
    # Explicit GZIP headers
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"
    
    # Cache headers that performance tools recognize
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"
    Cache-Control = "public, max-age=31536000"
    
    # Security
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.html"
  [headers.values]
    Expires = "Thu, 10 Jul 2025 23:59:59 GMT"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"
    Cache-Control = "public, max-age=31536000"
